// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVideoActivityForFamily = `-- name: GetVideoActivityForFamily :many
SELECT
    u.id AS user_id,
    u.role,
    (vl.id IS NOT NULL)::bool AS liked,
    COALESCE(wp.watched_seconds, 0)::int AS watched_seconds,
    wp.last_updated_at
FROM users u
LEFT JOIN video_likes vl ON vl.user_id = u.id AND vl.video_id = $2
LEFT JOIN watch_progress wp ON wp.user_id = u.id AND wp.video_id = $2
WHERE u.family_id = $1
ORDER BY u.created_at ASC
`

type GetVideoActivityForFamilyParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	VideoID  pgtype.UUID `json:"video_id"`
}

type GetVideoActivityForFamilyRow struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Role           ParentRole         `json:"role"`
	Liked          bool               `json:"liked"`
	WatchedSeconds int32              `json:"watched_seconds"`
	LastUpdatedAt  pgtype.Timestamptz `json:"last_updated_at"`
}

func (q *Queries) GetVideoActivityForFamily(ctx context.Context, arg GetVideoActivityForFamilyParams) ([]GetVideoActivityForFamilyRow, error) {
	rows, err := q.db.Query(ctx, getVideoActivityForFamily, arg.FamilyID, arg.VideoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVideoActivityForFamilyRow
	for rows.Next() {
		var i GetVideoActivityForFamilyRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Liked,
			&i.WatchedSeconds,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
