// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: children.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChild = `-- name: CreateChild :one
INSERT INTO children (name, date_of_birth)
VALUES ($1, $2)
RETURNING id, name, date_of_birth, created_at
`

type CreateChildParams struct {
	Name        string      `json:"name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, createChild, arg.Name, arg.DateOfBirth)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateOfBirth,
		&i.CreatedAt,
	)
	return i, err
}

const getChild = `-- name: GetChild :one
SELECT id, name, date_of_birth, created_at FROM children
WHERE id = $1
`

func (q *Queries) GetChild(ctx context.Context, id pgtype.UUID) (Child, error) {
	row := q.db.QueryRow(ctx, getChild, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateOfBirth,
		&i.CreatedAt,
	)
	return i, err
}
