// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMasterclass = `-- name: GetMasterclass :one
SELECT id, title, description, created_at FROM masterclasses
WHERE id = $1
`

func (q *Queries) GetMasterclass(ctx context.Context, id pgtype.UUID) (Masterclass, error) {
	row := q.db.QueryRow(ctx, getMasterclass, id)
	var i Masterclass
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, duration_seconds, masterclass_id, video_url, created_at FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DurationSeconds,
		&i.MasterclassID,
		&i.VideoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listMasterclasses = `-- name: ListMasterclasses :many
SELECT id, title, description, created_at FROM masterclasses
ORDER BY created_at ASC
`

func (q *Queries) ListMasterclasses(ctx context.Context) ([]Masterclass, error) {
	rows, err := q.db.Query(ctx, listMasterclasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Masterclass
	for rows.Next() {
		var i Masterclass
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByMasterclass = `-- name: ListVideosByMasterclass :many
SELECT id, title, duration_seconds, masterclass_id, video_url, created_at FROM videos
WHERE masterclass_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVideosByMasterclass(ctx context.Context, masterclassID pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByMasterclass, masterclassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DurationSeconds,
			&i.MasterclassID,
			&i.VideoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
