// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: families.sql

package sqlc

import (
	"context"
)

const createFamily = `-- name: CreateFamily :one
INSERT INTO families DEFAULT VALUES
RETURNING id, created_at
`

func (q *Queries) CreateFamily(ctx context.Context) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily)
	var i Family
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
