// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invite_codes (code, generated_by_user_id, child_id)
VALUES ($1, $2, $3)
RETURNING id, code, generated_by_user_id, redeemed_by_user_id, child_id, created_at, redeemed_at
`

type CreateInviteParams struct {
	Code              string      `json:"code"`
	GeneratedByUserID pgtype.UUID `json:"generated_by_user_id"`
	ChildID           pgtype.UUID `json:"child_id"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (InviteCode, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.Code, arg.GeneratedByUserID, arg.ChildID)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GeneratedByUserID,
		&i.RedeemedByUserID,
		&i.ChildID,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, generated_by_user_id, redeemed_by_user_id, child_id, created_at, redeemed_at FROM invite_codes
WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GeneratedByUserID,
		&i.RedeemedByUserID,
		&i.ChildID,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const getInviteByCodeForUpdate = `-- name: GetInviteByCodeForUpdate :one
SELECT id, code, generated_by_user_id, redeemed_by_user_id, child_id, created_at, redeemed_at FROM invite_codes
WHERE code = $1
FOR UPDATE
`

func (q *Queries) GetInviteByCodeForUpdate(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, getInviteByCodeForUpdate, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GeneratedByUserID,
		&i.RedeemedByUserID,
		&i.ChildID,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const redeemInvite = `-- name: RedeemInvite :one
UPDATE invite_codes
SET redeemed_by_user_id = $2,
    redeemed_at = now()
WHERE id = $1
  AND redeemed_by_user_id IS NULL
RETURNING id, code, generated_by_user_id, redeemed_by_user_id, child_id, created_at, redeemed_at
`

type RedeemInviteParams struct {
	ID               pgtype.UUID `json:"id"`
	RedeemedByUserID pgtype.UUID `json:"redeemed_by_user_id"`
}

func (q *Queries) RedeemInvite(ctx context.Context, arg RedeemInviteParams) (InviteCode, error) {
	row := q.db.QueryRow(ctx, redeemInvite, arg.ID, arg.RedeemedByUserID)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GeneratedByUserID,
		&i.RedeemedByUserID,
		&i.ChildID,
		&i.CreatedAt,
		&i.RedeemedAt,
	)
	return i, err
}
