// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLike = `-- name: GetLike :one
SELECT id, user_id, video_id, created_at FROM video_likes
WHERE user_id = $1 AND video_id = $2
`

type GetLikeParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) GetLike(ctx context.Context, arg GetLikeParams) (VideoLike, error) {
	row := q.db.QueryRow(ctx, getLike, arg.UserID, arg.VideoID)
	var i VideoLike
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.CreatedAt,
	)
	return i, err
}

const likeVideo = `-- name: LikeVideo :exec
INSERT INTO video_likes (user_id, video_id)
VALUES ($1, $2)
ON CONFLICT (user_id, video_id) DO NOTHING
`

type LikeVideoParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) LikeVideo(ctx context.Context, arg LikeVideoParams) error {
	_, err := q.db.Exec(ctx, likeVideo, arg.UserID, arg.VideoID)
	return err
}

const unlikeVideo = `-- name: UnlikeVideo :exec
DELETE FROM video_likes
WHERE user_id = $1 AND video_id = $2
`

type UnlikeVideoParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) UnlikeVideo(ctx context.Context, arg UnlikeVideoParams) error {
	_, err := q.db.Exec(ctx, unlikeVideo, arg.UserID, arg.VideoID)
	return err
}
