// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: masterclass_progress.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMasterclassProgressForFamily = `-- name: GetMasterclassProgressForFamily :many
SELECT
    mc.id AS masterclass_id,
    u.id AS user_id,
    u.role,
    COUNT(v.id)::int AS total_videos,
    COUNT(*) FILTER (WHERE wp.watched_seconds + $1::int >= v.duration_seconds)::int AS completed_videos
FROM masterclasses mc
CROSS JOIN users u
LEFT JOIN videos v ON v.masterclass_id = mc.id
LEFT JOIN watch_progress wp ON wp.user_id = u.id AND wp.video_id = v.id
WHERE u.family_id = $2
GROUP BY mc.id, u.id, u.role
ORDER BY mc.id
`

type GetMasterclassProgressForFamilyParams struct {
	CompletionGraceSeconds int32       `json:"completion_grace_seconds"`
	FamilyID               pgtype.UUID `json:"family_id"`
}

type GetMasterclassProgressForFamilyRow struct {
	MasterclassID   pgtype.UUID `json:"masterclass_id"`
	UserID          pgtype.UUID `json:"user_id"`
	Role            ParentRole  `json:"role"`
	TotalVideos     int32       `json:"total_videos"`
	CompletedVideos int32       `json:"completed_videos"`
}

func (q *Queries) GetMasterclassProgressForFamily(ctx context.Context, arg GetMasterclassProgressForFamilyParams) ([]GetMasterclassProgressForFamilyRow, error) {
	rows, err := q.db.Query(ctx, getMasterclassProgressForFamily, arg.CompletionGraceSeconds, arg.FamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMasterclassProgressForFamilyRow
	for rows.Next() {
		var i GetMasterclassProgressForFamilyRow
		if err := rows.Scan(
			&i.MasterclassID,
			&i.UserID,
			&i.Role,
			&i.TotalVideos,
			&i.CompletedVideos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
