// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ParentRole string

const (
	ParentRoleMom      ParentRole = "mom"
	ParentRoleDad      ParentRole = "dad"
	ParentRoleGuardian ParentRole = "guardian"
)

func (e *ParentRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParentRole(s)
	case string:
		*e = ParentRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ParentRole: %T", src)
	}
	return nil
}

type NullParentRole struct {
	ParentRole ParentRole `json:"parent_role"`
	Valid      bool       `json:"valid"` // Valid is true if ParentRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParentRole) Scan(value interface{}) error {
	if value == nil {
		ns.ParentRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParentRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParentRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParentRole), nil
}

type Child struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type InviteCode struct {
	ID                pgtype.UUID        `json:"id"`
	Code              string             `json:"code"`
	GeneratedByUserID pgtype.UUID        `json:"generated_by_user_id"`
	RedeemedByUserID  pgtype.UUID        `json:"redeemed_by_user_id"`
	ChildID           pgtype.UUID        `json:"child_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RedeemedAt        pgtype.Timestamptz `json:"redeemed_at"`
}

type Masterclass struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PartnerRelationship struct {
	ID       pgtype.UUID        `json:"id"`
	UserID1  pgtype.UUID        `json:"user_id_1"`
	UserID2  pgtype.UUID        `json:"user_id_2"`
	ChildID  pgtype.UUID        `json:"child_id"`
	LinkedAt pgtype.Timestamptz `json:"linked_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         ParentRole         `json:"role"`
	ChildID      pgtype.UUID        `json:"child_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Video struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	DurationSeconds int32              `json:"duration_seconds"`
	MasterclassID   pgtype.UUID        `json:"masterclass_id"`
	VideoUrl        string             `json:"video_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type VideoLike struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	VideoID   pgtype.UUID        `json:"video_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WatchProgress struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	VideoID        pgtype.UUID        `json:"video_id"`
	WatchedSeconds int32              `json:"watched_seconds"`
	LastUpdatedAt  pgtype.Timestamptz `json:"last_updated_at"`
}
