// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partners.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPartnerForUser = `-- name: GetPartnerForUser :one
SELECT id, user_id_1, user_id_2, child_id, linked_at FROM partner_relationships
WHERE user_id_1 = $1 OR user_id_2 = $1
`

func (q *Queries) GetPartnerForUser(ctx context.Context, userID1 pgtype.UUID) (PartnerRelationship, error) {
	row := q.db.QueryRow(ctx, getPartnerForUser, userID1)
	var i PartnerRelationship
	err := row.Scan(
		&i.ID,
		&i.UserID1,
		&i.UserID2,
		&i.ChildID,
		&i.LinkedAt,
	)
	return i, err
}

const insertPartner = `-- name: InsertPartner :one
INSERT INTO partner_relationships (user_id_1, user_id_2, child_id)
VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid), $3)
RETURNING id, user_id_1, user_id_2, child_id, linked_at
`

type InsertPartnerParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	ChildID pgtype.UUID `json:"child_id"`
}

func (q *Queries) InsertPartner(ctx context.Context, arg InsertPartnerParams) (PartnerRelationship, error) {
	row := q.db.QueryRow(ctx, insertPartner, arg.Column1, arg.Column2, arg.ChildID)
	var i PartnerRelationship
	err := row.Scan(
		&i.ID,
		&i.UserID1,
		&i.UserID2,
		&i.ChildID,
		&i.LinkedAt,
	)
	return i, err
}
