// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWatchProgress = `-- name: GetWatchProgress :one
SELECT id, user_id, video_id, watched_seconds, last_updated_at FROM watch_progress
WHERE user_id = $1 AND video_id = $2
`

type GetWatchProgressParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	VideoID pgtype.UUID `json:"video_id"`
}

func (q *Queries) GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRow(ctx, getWatchProgress, arg.UserID, arg.VideoID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.WatchedSeconds,
		&i.LastUpdatedAt,
	)
	return i, err
}

const upsertWatchProgress = `-- name: UpsertWatchProgress :one
INSERT INTO watch_progress (user_id, video_id, watched_seconds, last_updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id, video_id)
DO UPDATE SET
    watched_seconds = GREATEST(watch_progress.watched_seconds, EXCLUDED.watched_seconds),
    last_updated_at = CASE
        WHEN EXCLUDED.watched_seconds > watch_progress.watched_seconds THEN now()
        ELSE watch_progress.last_updated_at
    END
RETURNING id, user_id, video_id, watched_seconds, last_updated_at
`

type UpsertWatchProgressParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	VideoID        pgtype.UUID `json:"video_id"`
	WatchedSeconds int32       `json:"watched_seconds"`
}

func (q *Queries) UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRow(ctx, upsertWatchProgress, arg.UserID, arg.VideoID, arg.WatchedSeconds)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.WatchedSeconds,
		&i.LastUpdatedAt,
	)
	return i, err
}
