// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, family_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, family_id, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         ParentRole  `json:"role"`
	FamilyID     pgtype.UUID `json:"family_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FamilyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, family_id, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, family_id, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByFamilyID = `-- name: ListUsersByFamilyID :many
SELECT id, email, password_hash, role, family_id, created_at FROM users
WHERE family_id = $1
`

func (q *Queries) ListUsersByFamilyID(ctx context.Context, familyID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.FamilyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserFamily = `-- name: UpdateUserFamily :one
UPDATE users
SET family_id = $2
WHERE id = $1
RETURNING id, email, password_hash, role, family_id, created_at
`

type UpdateUserFamilyParams struct {
	ID       pgtype.UUID `json:"id"`
	FamilyID pgtype.UUID `json:"family_id"`
}

func (q *Queries) UpdateUserFamily(ctx context.Context, arg UpdateUserFamilyParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFamily, arg.ID, arg.FamilyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FamilyID,
		&i.CreatedAt,
	)
	return i, err
}
